# Generated by Django 2.2 on 2019-04-25 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('auther', models.CharField(max_length=64)),
                ('abstract', models.TextField()),
                ('content', models.TextField()),
                ('readnum', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('a_t', models.ManyToManyField(to='blog.Tag')),
                ('a_u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sortid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Sort')),
            ],
        ),
    ]
